### ISSUE TITLE
use another name than paint

### ISSUE THREAD

**Issue by freddii** [maifeeulasad/Paint#11]
I think renaming easypaint to paint might not be the best idea.
There is already a program for painting that is called paint.
https://en.wikipedia.org/wiki/Microsoft_Paint
Why not just maintain a simple fork?

**Comment by maifeeulasad** [comment]
@freddii I already have a fork : https://github.com/maifeeulasad/EasyPaint
As @Gr1N [mentioned](https://github.com/Gr1N/EasyPaint/issues/155#issuecomment-745447793) he has lost interest, that's why I'm creating a new one. I'll personally keep pushing to my fork and new features will be introduced here. And we are discussing about the [name issue](https://github.com/maifeeulasad/Paint/issues/10#issuecomment-746070006).
